### ISSUE TITLE
Cleanup media resources when VoiceInterpreter fails to download RCML

### ISSUE THREAD

**Issue by hrosa** [RestComm/RestComm-Core#736] opened 2015-12-15 15:40 UTC
When performing outbound calls via REST API, I noticed that RestComm is unable to clean media resources if the Voice Interpreter fails to download the RCML specified in the HTTP request (Url parameter)

**Comment by gvagenas** [comment] 2016-01-12 16:48
duplicate of #689

**Closed by gvagenas** 2016-01-12 16:48 UTC
Labels: 1. Bug, 3. Duplicate, Core engine, Normal-Priority, XMS-1.0.0
